# Generated by Django 3.1.2 on 2020-11-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_comment_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='comment_image')),
                ('comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referenceComment', to='comments.comment')),
            ],
            options={
                'db_table': 'comment_meta',
            },
        ),
    ]
