# Generated by Django 3.1.2 on 2020-11-08 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='upload_profile',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userprofileimage', to='user.user'),
        ),
    ]
