# Generated by Django 3.1.2 on 2020-11-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201108_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
