# Generated by Django 3.1.2 on 2020-11-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201119_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_recipe',
        ),
    ]
