# Generated by Django 3.1.2 on 2020-11-08 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0001_initial'),
        ('upload', '0003_auto_20201108_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_recipe',
            name='recipe_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipeimage', to='recipe_blog.recipe'),
        ),
        migrations.AddField(
            model_name='upload_recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_image'),
        ),
        migrations.AddField(
            model_name='upload_recipe',
            name='step_id',
            field=models.IntegerField(default=1),
        ),
    ]
