# Generated by Django 3.1.2 on 2020-11-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20201108_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_recipe',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
