# Generated by Django 3.1.2 on 2020-10-29 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
