# Generated by Django 3.1.2 on 2020-11-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201107_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_recipe',
            field=models.IntegerField(default=0),
        ),
    ]
