# Generated by Django 3.1.2 on 2020-11-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_image',
            field=models.ImageField(blank=True, null=True, upload_to='step_image'),
        ),
    ]
