# Generated by Django 3.1.2 on 2020-11-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('introduction', models.CharField(max_length=1024)),
                ('gender', models.CharField(max_length=30)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('total_follower', models.IntegerField(default=0)),
                ('total_followering', models.IntegerField(default=0)),
                ('avatar', models.FileField(default='default.png', max_length=300, upload_to='avatar/')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_calendar',
            },
        ),
        migrations.CreateModel(
            name='User_follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_follow',
            },
        ),
    ]
