# Generated by Django 3.1.2 on 2020-11-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('introduction', models.CharField(blank=True, max_length=1024)),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('total_follower', models.IntegerField(default=0)),
                ('total_following', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.user')),
            ],
            options={
                'db_table': 'user_follow',
            },
        ),
    ]
