# Generated by Django 3.1.2 on 2020-11-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('introduction', models.CharField(max_length=1024)),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('total_follower', models.IntegerField()),
                ('avatar', models.FileField(max_length=300, upload_to='../upload/avatar')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
