# Generated by Django 3.1.2 on 2020-11-07 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='../upload/avatar/default.png', max_length=300, upload_to='../upload/avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_follower',
            field=models.IntegerField(default=0),
        ),
    ]
