# Generated by Django 3.1.2 on 2020-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201107_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatar/default.png', max_length=300, upload_to='avatar/'),
        ),
    ]
