# Generated by Django 3.1.2 on 2020-11-09 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default="It's a recipe", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='update_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 11, 9, 6, 33, 7, 103591)),
            preserve_default=False,
        ),
    ]
